// Bundles the whole tuner into one self-contained HTML file.
//
//   node tools/build-single.mjs   ->  tuner.html
//
// The worklet and worker still need to be loaded from URLs (that is what
// addModule and the Worker constructor take), so they are carried in the page
// as inert <script> blocks and turned into blob: URLs at runtime. The WASM
// binary rides along as base64 and is handed to the worker as bytes, so
// nothing is fetched at all.

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const read = (p) => readFile(fileURLToPath(new URL(p, root)), 'utf8');

/** Turn an ES module into a plain script body. */
const flatten = (source) => source
  .replace(/^import[^\n]*\n/gm, '')
  .replace(/^export /gm, '')
  .trim();

const [html, wasm, worklet, worker, music, audio, app] = await Promise.all([
  read('index.html'),
  readFile(fileURLToPath(new URL('wasm/yin.wasm', root))),
  read('src/capture-processor.js'),
  read('src/detector-worker.js'),
  read('src/music.js'),
  read('src/audio.js'),
  read('src/app.js'),
]);

for (const [name, source] of [['worklet', worklet], ['worker', worker]]) {
  if (source.includes('</script')) throw new Error(`${name} source contains </script`);
}

const bundle = `
<!-- Carried as inert script blocks: the browser ignores unknown types, and
     addModule() / new Worker() need URLs, which we mint from these below. -->
<script type="text/x-audioworklet" id="src-capture-processor">
${worklet}
</script>

<script type="text/x-worker" id="src-detector-worker">
${worker}
</script>

<script>
// ---------------------------------------------------------------------------
// Generated by tools/build-single.mjs — edit the files in src/ and wasm/, then
// rebuild. Everything below is inlined so this page works from any static host
// with no other files beside it.
// ---------------------------------------------------------------------------

/** wasm/yin.wasm, base64 (${wasm.length} bytes decoded) */
const EMBEDDED_WASM = "${wasm.toString('base64')}";

function base64ToBytes(base64) {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function blobUrlFrom(elementId) {
  const source = document.getElementById(elementId).textContent;
  return URL.createObjectURL(new Blob([source], { type: 'text/javascript' }));
}

/** Single-file replacement for src/sources.js. */
function resolveSources() {
  return {
    workletUrl: blobUrlFrom('src-capture-processor'),
    workerUrl: blobUrlFrom('src-detector-worker'),
    wasmBytes: base64ToBytes(EMBEDDED_WASM),
  };
}

// --- src/music.js ----------------------------------------------------------
${flatten(music)}

// --- src/audio.js ----------------------------------------------------------
${flatten(audio)}

// --- src/app.js ------------------------------------------------------------
${flatten(app)}
</script>
`.trim();

const out = html.replace('<script type="module" src="./src/app.js"></script>', bundle);
if (out === html) throw new Error('could not find the module script tag in index.html');

const path = fileURLToPath(new URL('tuner.html', root));
await writeFile(path, out);
console.log(`built tuner.html (${(out.length / 1024).toFixed(1)} KB, single file, no dependencies)`);
